// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzl9wSIfGGl8IqlHF5pUwI49w6oICfW1o',
    appId: '1:591815313999:android:ef55fee111f55fb4acf83a',
    messagingSenderId: '591815313999',
    projectId: 'pantry-manager-1f66f',
    storageBucket: 'pantry-manager-1f66f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiSIkmH_Hq1mDdoMZXc3mkj-iwklR7qgQ',
    appId: '1:591815313999:ios:c6f1f940dd962d00acf83a',
    messagingSenderId: '591815313999',
    projectId: 'pantry-manager-1f66f',
    storageBucket: 'pantry-manager-1f66f.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJY1c1aLmQAcGW_m6KcQJYkqDiCl_o2mc',
    appId: '1:591815313999:web:99b518bf3b6f1f49acf83a',
    messagingSenderId: '591815313999',
    projectId: 'pantry-manager-1f66f',
    authDomain: 'pantry-manager-1f66f.firebaseapp.com',
    storageBucket: 'pantry-manager-1f66f.firebasestorage.app',
    measurementId: 'G-GWBQVN5ZBS',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJY1c1aLmQAcGW_m6KcQJYkqDiCl_o2mc',
    appId: '1:591815313999:web:3e7d7623e6e009a4acf83a',
    messagingSenderId: '591815313999',
    projectId: 'pantry-manager-1f66f',
    authDomain: 'pantry-manager-1f66f.firebaseapp.com',
    storageBucket: 'pantry-manager-1f66f.firebasestorage.app',
    measurementId: 'G-FP3N9V5EQB',
  );

}